language: java

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk11
- openjdk8
- openjdk9
- openjdk10
- openjdk11

env:
  global:
  - secure: e96kKaqQiFpH1leNnf/NFd+CqWSBJYjmD6Hg8Bbbqo22Sq4cL/jFw2V0hzJiSBYpqIwnyifZWe2FaU0TRee/ne1bHcpUbxLXItkWuUjjPGeVEtS78uQwJ9vC+UpU+MF6mU0uIKF7PrFTbfxJIN6i/kfe2OC83E1m7fLrd8dY7UanaKYN6xw5t3lj0KEuycb2zwxRifTDEITe5F1szmukTf4FMmN611JoUSZtYVxGDyB5okfrlJDkBV2AvkfaUHQ2+MlPkIopHtn22WPghJ30FJs9k5/txQ9ixRBC9F6V5BR5prbOXhWrabKpUA4nuXB1GlRKW0yZa6QLeJDkQrX/WHb3+fIBsgXS4us/jB7vxRj9Hdgzk2PHMSNvTiZyap0GL5roMMHRA+kdgfe3N1vASC78Z8DcQjE5N7qkyECNm5YFBzrYs7MKJiJV3efiPTI+R5HWA4diaDP7Ex+/OetD+aDP+NRXjbIGnXlVi5UTl12UMFsFZIyyM9Jc7lU1RMYTWQ+UHztU1abXltR1oeljTECt6yqNKB5BT3s3QK9XkRFqIgTQefA2b7Lr3FPSc/iFQft3SFwTGl+caogFuZyaYp0f8KC7Ib08bdYekvAp7kVFefbDqXjV3zyX8h8sa2M1EmILp+YOepICzZguT4AtOJl9fAbrhgyedFisoNIrmao=
  - secure: mqRaJkqnq9AKRywhPM94KklLRMzdXOzPh17Fe1qLrcuZjdozOZet6Ooj6TmjBBp7FxpYE/lB0g0Zs3sOiRFM/+0cZY1Y6Q1welHFJn4OpdAS7jQJsAfeRFuKLSApFnstKJV7kGTzrQZG6uGt5z/lqj2udYU0nbZvpLS2EEzB9NirX9dV5Cwuqd2X2cLvp6Qf57RQ7OL1aVx7A8vqZ/MsEGzPLqIAac44/RYzN2/bmRV7YkRK87p5dQMZ9MoAVlfzNBOi42JVJmjAr2I9Uh8jWxKPUvVTBPJG+9iBJqPQruGDlnycRQRUGzFATDpMPWFkjAJhdkR626Uocr+Y/XZ8kPDw5iBuqg9YNAQhzF83yLZx3CfdSG5T9Wws6tAo5sIXm+Tb1AcPMUS0KZQAZr1aHaTM2CZuoDPyk37VLJJcuiusYmal0/UAF/b+tZkxJq5gXfxswC+VnqBjGpj/Ju5d2U0wtoF52HwNtZGmK2JeKGVXuLu1EU9Bz3bhgV/bHHYZQGnJJ3jR1ErSpCUZME9ClzpFsTzURCkjQPKF+wbWfVqs6hOy8JUD331lxBwpCdpT6sAtLvNzoHxJral5hiMmoyaZmr4a8vxpZkAgG6gfFRLunsbfIBeG9r4BJB8zDic5MD68OuhIQJMA/fpj6adjppQ+TjGbGpWi13PWLGZRoks=
  - secure: Wz0f38v4GvumplPM85/0xvMjp6c9wLKnHz99hHlTk5nSDvXrmGK0YJ402vrd1D0sFxjA9kBhqYgypYTlVOR4jyD6nAPVpqoKGiqno+sJ4ehUjHNLDNGIYw5vgqoJPmin1tKOzDVN7NbCdThqfTgRqy12BcJ80VoeXeW+AlOU7yMDdZe1arv/BokIEsHxQ+aeM5QdZ0b3XfEzCv9ISRN94Pc51ihh3II/X7aT/nAedzdo/J7E07Z1V8PY03RPdG2rEGdX3fjkVpgOixJwBb10j+IJc+gohq/MZBeESPaBlYnGvqtffa8fH54jEMvi1YAzmdxUwStJWV7RgoqjzwoZGXkPoEBgUjOe74qMkhyw0sbERDz/5bFREm9F1VRR4TlpNXCoLMcEHgaOSNp6EyL8LgNsHGdxrCJyZT2XIwLpMoyk169EDkfRsHjG82eKfWUF54oayVNSA5100St6CP+4zAkrwopPBkMgRanhqmhUMAsRalOvEx9NleHFahRiPESJPRz/tFlfnB2QG8Jnek+b0bKmsP6RCZS5A1RZEjC2R2qtdZ8393FSnWW/dapz/SDdkp+9BDKVR4+WBloEwm6Osf7kPVg76dwlj9HYrYy/2DC09Q40xETanTLoMFM42MuHkcLOfhwitpVD/y9kxoS6V4bqIiZxIDqiHMVe65EaIGg=
  - secure: fvj5ZVZ/s/YY/5zIGUtQkPtxNJcSH5I5UR3bZmS1VijPAgjlepw25mX4jEpeltN9qyEMmn8dnRWQz/EeZzky7EgaXop7hWJjXNj7EBgTFBdCpgciX/MWewLyloWlUcOUuiV2hznDh2sxGk9tty8sbnF7amCT5fIGQs4OmmVsZTpTpLPnH1ODqA/Up2xdFEaZLzkC/ps80ltToox1rXHCLBTa59zCNkRkiiHv270ueXBreoG7MTlfX8PfgblXPKaYjxNCjMd4gWOx9pqH6Ld+iSodCXzKzCiWjCyLanpQuySSSXF5nSbUsileLHdwz0ET2U3zNqbvo6Bals+GDuJYCkXCJ+O0wq8CU5RBPSjFSStRqqN3xsgqIh1SpDb+vuVo5N84pz9rmZSU731wmAO/TYnLJvYiEdqhjPNpSTVQZrfNg0f5+AoQgf0qOtz/jizlGLDwDsFkQGpYIPWsNwQMY6Ko0zsHWxXlRYc3T++M9JW0ACOAz0IuLPjrNfLdZD8+4F0cQe+MbpLtlGZ2w+3QsmLccAY/lRK9JGtjWdO4pTM6wP682ijZqaY+R0v2fGfcc5ML6VAsXW3elCWyRMCr8x++nE+C4mNA+OtKR+gJ6hGSHZkYNEDUVyvWTIABSRXZuJlt9/fFigPSksEurVUqohFz/hEUPsplNOUeQzOs9rk=

install:
- "./mvnw -T4 -Dmaven.test.skip=true install"

jobs:
  include:
  - stage: test
    script: "./mvnw -P with-e2e-tests verify"
  - stage: deploy
    sudo: false
    services: []
    install: skip
    script: skip
    deploy:
      provider: script
      script: release/deploy.sh
      on:
        tags: true
        branch: master
        jdk: openjdk11
        condition: $TRAVIS_OS_NAME = linux
